version: '3.6'

services:

  goshop:
    container_name: goshop
    logging:
      options:
        max-size: 2048m
        max-file: "2"
    build:
      context: .
    ports:
      - $APP_PORT:8000
    volumes:
      - gopath:/go
    network_mode: bridge


volumes:
  gopath: